title: Gaurav Bosamiya
# logo : /assets/img/g.jpg
# show_downloads: true
theme: jekyll-theme-architect
github: https://github.com/gauravbosamiya
linkedin: https://www.linkedin.com/in/gaurav-bosamiya-702540260/
# instagram: https://www.instagram.com/_gauravvv_9/
# youtube: https://www.youtube.com/channel/UCnJ817GHftebmIegdxr6NCQ
email: gauravbosamiya9@gmail.com
# website: https://gauravportfolioweb.netlify.app/
